// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OstaFeedbackApp.Data;

#nullable disable

namespace OstaFeedbackApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // =============================
            // FEEDBACK TABLE
            // =============================
            modelBuilder.Entity("OstaFeedbackApp.Models.Feedback", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("AgeGroup").HasColumnType("text");
                b.Property<int>("Commitment").HasColumnType("integer");
                b.Property<int>("CommunityImpact").HasColumnType("integer");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Department").HasColumnType("text");
                b.Property<string>("DigitalService").HasColumnType("text");
                b.Property<string>("Impressed").HasColumnType("text");
                b.Property<string>("Improvement").HasColumnType("text");
                b.Property<int>("Innovation").HasColumnType("integer");
                b.Property<string>("Occupation").HasColumnType("text");
                b.Property<string>("Region").HasColumnType("text");
                b.Property<int>("Transparency").HasColumnType("integer");
                b.Property<string>("VisitorType").HasColumnType("text");
                b.Property<int>("YouthOpportunity").HasColumnType("integer");
                b.Property<string>("YouthSupport").HasColumnType("text");

                b.HasKey("Id");
                b.ToTable("Feedbacks");
            });

            // =============================
            // QUESTIONS TABLE (IMPORTANT)
            // =============================
            modelBuilder.Entity("OstaFeedbackApp.Models.Question", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<bool>("IsEnabled").HasColumnType("boolean");
                b.Property<bool>("IsRequired").HasColumnType("boolean");
                b.Property<int>("MaxRating").HasColumnType("integer");

                b.Property<string>("Property")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TextAm").IsRequired().HasColumnType("text");
                b.Property<string>("TextEn").IsRequired().HasColumnType("text");
                b.Property<string>("TextOr").IsRequired().HasColumnType("text");

                b.HasKey("Id");
                b.ToTable("Questions");
            });

#pragma warning restore 612, 618
        }
    }
}
